"""
BuildCaseCmd.py -- run inside FreeCAD (GUI or freecadcmd).

Creates / refreshes the document "SWC_Enclosure" containing:

    Parameters   Spreadsheet   -- every driving parameter, named for editing
    Case_Body    Part::Feature -- the base solid
    Case_Lid     Part::Feature -- the lid solid
    Logo_Inlay   Part::Feature -- third body: the OET logo, printed in a
                                  contrasting colour and dropped into the
                                  lid's pocket flush with its top face

The B-rep is generated by build_case.py from casegeom.py, which is the single
source of truth: change a value in casegeom.py and re-run this to regenerate.
The spreadsheet mirrors the parameters so they are visible/editable in the GUI.

Usage in the FreeCAD Python console:
    exec(open('/path/to/plastic_case/BuildCaseCmd.py').read())
"""
import os
import sys
import time

import FreeCAD as App
import Part
import Spreadsheet

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

DOCNAME = "SWC_Enclosure"

# --- (re)create the document -------------------------------------------------
if DOCNAME in [d.Name for d in App.listDocuments().values()] or \
        App.ActiveDocument and App.ActiveDocument.Name == DOCNAME:
    App.closeDocument(DOCNAME)
doc = App.newDocument(DOCNAME)
App.setActiveDocument(DOCNAME)

# --- spreadsheet of parameters ----------------------------------------------
import casegeom as G

sheet = doc.addObject("Spreadsheet::Sheet", "Parameters")
rows = [
    ("Board outline x0", G.BOARD_X0),
    ("Board outline x1", G.BOARD_X1),
    ("Board outline y0", G.BOARD_Y0),
    ("Board outline y1", G.BOARD_Y1),
    ("Board thickness", G.BOARD_T),
    ("Wall thickness", G.WALL),
    ("Case x0", G.CASE_X0),
    ("Case x1", G.CASE_X1),
    ("Case y0 (nose)", G.CASE_Y0),
    ("Case y1", G.CASE_Y1),
    ("Cavity x0", G.CAV_X0),
    ("Cavity x1", G.CAV_X1),
    ("Cavity y0 (nose)", G.CAV_Y0),
    ("Cavity y1", G.CAV_Y1),
    ("Lid top z", G.Z_LID_TOP),
    ("Rim z", G.Z_RIM),
    ("Spigot bottom z", G.Z_SPIGOT),
    ("Floor top z", G.Z_FLOOR_TOP),
    ("Foot z (case bottom)", G.Z_FOOT),
    ("Pilot floor z (blind)", G.PILOT_FLOOR_Z),
    ("M5 pilot dia", G.PILOT_D),
    ("Boss dia", G.BOSS_D),
    ("Tower dia", G.TOWER_D),
    ("M5 screw length", G.SCREW_LEN),
    ("Counterbore dia", G.CBORE_D),
    ("Counterbore depth", G.CBORE_DEPTH),
    ("Counterbore rim raise", G.CBORE_RAISE),
    ("Wire window w", G.WIRE_WIN_W),
    ("Wire window z0", G.WIRE_WIN_Z0),
    ("Wire window z1", G.WIRE_WIN_Z1),
    ("Driver slot w", G.DRIVER_SLOT_W),
    ("Vent width", G.VENT_W),
    ("Vent height", G.VENT_H),
    ("Vent band z (low)", G.VENT_Z_LO),
    ("Buzzer body dia", G.BZ_BODY_D),
    ("Logo scale", G.LOGO_SCALE),
    ("Logo stroke widen", G.LOGO_WIDEN),
    ("Logo pocket depth", G.LOGO_DEPTH),
    ("Logo pocket gap", G.LOGO_GAP),
    ("Logo centre y", G.LOGO_Y),
    ("Case height", G.Z_LID_TOP - G.Z_FOOT),
]
sheet.set("A1", "Parameter")
sheet.set("B1", "Value")
for i, (k, v) in enumerate(rows, start=2):
    sheet.set("A%d" % i, k)
    sheet.set("B%d" % i, str(v))
sheet.setColumnWidth("A", 160)
sheet.setColumnWidth("B", 90)

# --- solids ------------------------------------------------------------------
import build_case as B

t = time.time()
base = B.build_base()
lid = B.build_lid()
logo = B.build_logo()

ob = doc.addObject("Part::Feature", "Case_Body")
ob.Shape = base
ob.Label = "Case_Body"
ol = doc.addObject("Part::Feature", "Case_Lid")
ol.Shape = lid
ol.Label = "Case_Lid"
# the lid and the inlay are modelled in their ASSEMBLY position already (the
# lid's sleeves start at board z 0, its flange at Z_RIM; the inlay sits in the
# pocket), so no placement is applied -- the three bodies stack correctly as-is.
ogo = doc.addObject("Part::Feature", "Logo_Inlay")
ogo.Shape = logo
ogo.Label = "Logo_Inlay"

doc.recompute()
try:
    import FreeCADGui
    FreeCADGui.ActiveDocument.ActiveView.viewAxonometric()
    FreeCADGui.SendMsgToActiveView("ViewFit")
except Exception:
    pass

print("SWC_Enclosure: %d objects, built in %.1fs" % (len(doc.Objects),
                                                    time.time() - t))
for o in doc.Objects:
    if not hasattr(o, "Shape") or o.Shape.isNull():
        print("  %-12s %s" % (o.Name, o.TypeId))
        continue
    bb = o.Shape.BoundBox
    print("  %-12s %-18s X %.2f..%.2f Y %.2f..%.2f Z %.2f..%.2f"
          % (o.Name, o.TypeId, bb.XMin, bb.XMax, bb.YMin, bb.YMax,
             bb.ZMin, bb.ZMax))
