#!/usr/bin/env python3
"""Generate include/Secrets.h from an untracked .env file.

WHY THIS EXISTS: the WiFi credentials live in swc_module_pcb/code/.env, which is
git-ignored there for good reason (its own header: "No credentials shall ever be
committed to git"). This project needs those values at build time, and the one
thing that must not happen is a copy of them landing in a tracked file here.

So the .env is read by this pre-build step and the generated header is
git-ignored. Nothing in the repository tree contains a credential.

Lookup order (first hit wins):
  1. ./.env                       -- local override, git-ignored
  2. ../swc_module_pcb/code/.env  -- the existing project's file
  3. environment variables          -- CI / one-off use

If nothing is found the header is still written, with empty strings, so the build
succeeds and the WiFi tests report "no credentials" rather than failing to
compile. A missing credential is a test result, not a build error.
"""

import os
import re
import sys

Import("env")  # noqa: F821 -- provided by PlatformIO's SCons environment

HERE = os.path.dirname(os.path.abspath(env["PROJECT_DIR"]))  # noqa: F821
PROJ = env["PROJECT_DIR"]  # noqa: F821

ENV_CANDIDATES = [
    os.path.join(PROJ, ".env"),
    os.path.join(os.path.dirname(PROJ), "swc_module_pcb", "code", ".env"),
]

WANTED = ["WIFI_SSID", "WIFI_PASSWORD"]


def parse_env_file(path):
    out = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                out[k.strip()] = v.strip().strip('"').strip("'")
    except OSError:
        return {}
    return out


def c_escape(s):
    """Escape for a C string literal. Refuses to emit a raw newline."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch in "\r\n":
            continue
        else:
            out.append(ch)
    return "".join(out)


def generate(source, target, env, **kwargs):
    """PlatformIO calls this as a pre-action with (source, target, env); the
    module also calls it directly at load time. Accept and ignore both."""
    del source, target, env, kwargs
    values = {}
    origin = "none"
    for path in ENV_CANDIDATES:
        parsed = parse_env_file(path)
        if parsed:
            values = parsed
            origin = path
            break

    for key in WANTED:
        if not values.get(key):
            v = os.environ.get(key, "")
            if v:
                values[key] = v
                origin = "environment"

    header = os.path.join(PROJ, "include", "Secrets.h")
    body = [
        "#pragma once",
        "// GENERATED by tools/gen_secrets.py -- DO NOT EDIT, DO NOT COMMIT.",
        "//",
        "// This file is git-ignored. It exists so the credentials never appear in",
        "// any tracked file. Regenerate by building; the pre-script rewrites it.",
        "//",
        "// Source: %s" % origin,
        "",
    ]
    for key in WANTED:
        body.append('#define SWC_%s "%s"' % (key, c_escape(values.get(key, ""))))
    body += [
        "",
        "// True when a value was actually found, so a test can report",
        "// 'not configured' rather than 'connect failed'.",
        "#define SWC_WIFI_CONFIGURED %d" % (1 if values.get("WIFI_SSID") else 0),
        "",
    ]

    new = "\n".join(body)
    old = None
    try:
        with open(header, "r", encoding="utf-8") as fh:
            old = fh.read()
    except OSError:
        pass

    if old != new:
        os.makedirs(os.path.dirname(header), exist_ok=True)
        with open(header, "w", encoding="utf-8") as fh:
            fh.write(new)
        sys.stderr.write(
            "[gen_secrets] wrote include/Secrets.h (source: %s, ssid: %s)\n"
            % (origin, "set" if values.get("WIFI_SSID") else "EMPTY")
        )


env.AddPreAction("buildprog", generate)  # noqa: F821
# Also run when the source list is resolved, so a plain `pio run` (which may not
# reach buildprog on an up-to-date tree) still has the header present.
generate(None, None, None)
