#include "Maintenance/WebPage.h"

#include <stdio.h>
#include <string.h>

#include "Maintenance/WebPageAssets.h"   // generated by tools/gen_assets.py
#include "Util/Sha256.h"

namespace {

// A different salt from the BLE PoP's. Reusing the PoP's salt would make the web
// token a prefix of the PoP, so anyone who read the token off a browser history
// would hold part of the provisioning secret.
constexpr char kTokenSalt[] = "swc-webtok-v1";

}  // namespace

bool WebTokenDerive(const uint8_t mac[6], char *out, size_t out_len) {
    if (mac == nullptr || out == nullptr) return false;
    // Twelve hex characters plus the terminator.
    if (out_len < kWebTokenLen + 1) return false;

    char material[64];
    const int n = snprintf(material, sizeof(material), "%s:%02X%02X%02X%02X%02X%02X",
                           kTokenSalt, mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    if (n <= 0 || static_cast<size_t>(n) >= sizeof(material)) return false;

    char hex[65];
    if (!Sha256Hex(reinterpret_cast<const uint8_t *>(material), strlen(material), hex)) {
        return false;
    }
    for (size_t i = 0; i < kWebTokenLen; ++i) {
        const char c = hex[i];
        out[i] = (c >= 'a' && c <= 'f') ? static_cast<char>(c - 'a' + 'A') : c;
    }
    out[kWebTokenLen] = '\0';
    return true;
}

bool WebTokenMatches(const char *presented, const char *expected) {
    if (presented == nullptr || expected == nullptr) return false;
    const size_t np = strlen(presented);
    const size_t ne = strlen(expected);
    // A length mismatch is itself a failure, but the comparison below still runs
    // over the expected length so the cost does not reveal where they diverge.
    if (ne == 0) return false;

    // Byte-at-a-time accumulate rather than memcmp: memcmp is allowed to stop at
    // the first differing byte, which leaks the prefix through timing.
    uint8_t diff = 0;
    for (size_t i = 0; i < ne; ++i) {
        // Reading past a shorter presented string would be out of bounds, so
        // substitute a byte that cannot match instead.
        const char p = (i < np) ? presented[i] : '\0';
        diff |= static_cast<uint8_t>(p ^ expected[i]);
    }
    return np == ne && diff == 0;
}

const WebAsset *WebPageFind(const char *path) {
    if (path == nullptr) return nullptr;
    for (size_t i = 0; i < kWebAssetCount; ++i) {
        if (strcmp(kWebAssets[i].path, path) == 0) return &kWebAssets[i];
    }
    return nullptr;
}

const char *WebPageContentType() {
    return "text/html; charset=utf-8";
}
