#!/usr/bin/env python3
"""Turn code/assets/*.html into a C++ array that lives in flash.

Spec 9.2's partition table has **no filesystem partition** -- nvs, otadata,
phy_init, two app slots, coredump, and nothing else -- so there is nowhere to
mount a filesystem from. The maintenance page is therefore compiled in.

Run by PlatformIO via `extra_scripts` before the build (see extra_assets.py), and
safe to run by hand. It is idempotent: the output depends only on the inputs, so
a clean checkout and a dirty one produce identical bytes.
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
ASSETS = HERE.parent / "assets"
OUT = HERE.parent / "lib" / "Maintenance" / "WebPageAssets.h"


def sanitize(name: str) -> str:
    """A C identifier from a filename. Non-alphanumerics become underscores."""
    return re.sub(r"[^0-9a-zA-Z_]", "_", name)


def main() -> int:
    files = sorted(ASSETS.glob("*.html"))
    if not files:
        print(f"gen_assets: no .html under {ASSETS}", file=sys.stderr)
        return 1

    lines = [
        "// GENERATED by tools/gen_assets.py -- do not edit by hand.",
        "// Edit code/assets/*.html and rebuild; a hand edit here is lost on the",
        "// next run and the page would silently diverge from its source.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
    ]

    entries = []
    for f in files:
        raw = f.read_bytes()
        # A page that is not valid UTF-8 would be sent as mojibake with no error;
        # refusing here keeps that out of the firmware.
        text = raw.decode("utf-8")
        # Escapes for a C++ string literal. The three that matter for HTML+JS are
        # the backslash, the double quote and the newline; a stray raw newline
        # inside a literal is a compile error, not a silent truncation.
        body = (
            text.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\r", "")
            .split("\n")
        )
        ident = sanitize(f.name)
        lines.append(f"inline constexpr char kAsset_{ident}[] =")
        for i, ln in enumerate(body):
            lines.append(f'    "{ln}\\n"')
        lines.append(";")
        lines.append("")
        entries.append((f.name, ident, len(raw)))
        print(f"gen_assets: {f.name} -> kAsset_{ident} ({len(raw)} bytes)")

    # A table rather than a single name, so adding a second asset does not need
    # the loader rewritten.
    lines.append("struct WebAsset {")
    lines.append("    const char *path;")
    lines.append("    const char *body;")
    lines.append("    size_t      len;")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr WebAsset kWebAssets[] = {")
    for name, ident, n in entries:
        lines.append(f'    {{"/{name}", kAsset_{ident}, sizeof(kAsset_{ident}) - 1}},')
    lines.append('    {"/", kAsset_index_html, sizeof(kAsset_index_html) - 1},')
    lines.append("};")
    lines.append("inline constexpr size_t kWebAssetCount = sizeof(kWebAssets) / sizeof(kWebAssets[0]);")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"gen_assets: wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
