#!/usr/bin/env python3
"""Generate `Update/BenchReleaseCa.h` -- a pinned CA for a BENCH release host, so
`tools/bench_ota_release.py` can prove the pin's ACCEPT/REJECT behaviour without a
published release.

Fetches `<host>:443`'s TLS chain, takes the ROOT certificate, and writes a header
defining `kReleaseCaPem` (the same symbol `Update/ReleaseCa.h` defines), so a build
with `-D SWC_BENCH_RELEASE_CA -I<outdir>` pins exactly that root.

Usage:
  python3 tools/gen_bench_ca.py <host> <outdir>
  # e.g. python3 tools/gen_bench_ca.py some-name.trycloudflare.com /tmp/benchca

Exit codes: 0 wrote the header, 2 environment / TLS error.
"""

import os
import re
import socket
import ssl
import sys
import pathlib


def fetch_root_pem(host, port=443):
    """Return the ROOT certificate of the host's presented chain, as PEM text."""
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE          # we WANT the unverified chain
    with socket.create_connection((host, port), timeout=10) as sock:
        with ctx.wrap_socket(sock, server_hostname=host) as ssock:
            der_chain = ssock.get_verified_chain() if hasattr(ssock, "get_verified_chain") \
                else None
    # `get_verified_chain()` is the whole chain but returns DER; fall back to
    # openssl for a portable PEM extraction.
    import subprocess
    p = subprocess.run(["openssl", "s_client", "-connect", f"{host}:{port}",
                        "-servername", host, "-showcerts"],
                       input=b"", capture_output=True, timeout=20)
    blocks = re.findall(rb"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",
                        p.stdout, re.S)
    if not blocks:
        raise RuntimeError(f"no certificates in {host}:{port}'s chain")
    root = blocks[-1].decode("ascii")
    return root


def write_header(pem, outdir):
    outdir = pathlib.Path(outdir)
    (outdir / "Update").mkdir(parents=True, exist_ok=True)
    body = "\n".join('    "%s\\n"' % line for line in pem.strip().splitlines())
    text = f"""#pragma once

/*
 * GENERATED by tools/gen_bench_ca.py -- DO NOT COMMIT. A bench build pins this
 * root (via -D SWC_BENCH_RELEASE_CA -I<outdir>) so the release fetch's pinned-CA
 * ACCEPT/REJECT behaviour can be exercised against a bring-up host without a
 * published release. Shipped builds never set the define and use the real
 * `Update/ReleaseCa.h`.
 */
static const char kReleaseCaPem[] =
{body};
"""
    path = outdir / "Update" / "BenchReleaseCa.h"
    path.write_text(text)
    return path


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    host, outdir = sys.argv[1], sys.argv[2]
    try:
        pem = fetch_root_pem(host)
    except Exception as e:
        print(f"ERROR: could not fetch the chain for {host}: {e}", file=sys.stderr)
        return 2
    path = write_header(pem, outdir)
    print(f"wrote {path} (root CA for {host})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
